### PR TITLE
Fix-file-locking

### LINKED ISSUE #85: CI sometimes hangs
See [8f0f4e9](https://github.com/DeepBlueRobotics/DeepBlueSim/pull/84/commits/8f0f4e956a15cf84ebb36e009b894c21bac6a2fa).

### LINKED ISSUE #90: Build hangs when previous build interrupted
It looks like PR #86 breaks things because gradle reuses build process and doesn't have a way to handle builds that are interrupted (eg with ctrl-c).

### PR DESCRIPTION
**Pull request by brettle**
Move file locking to WebotsSimulator to fix #90  and ensure endCompetition() is always called to at least partially fix #85.

Also makes WebotsSimulator constructor take the robot class instead of making the run() method take a robot instance. That helps discourage the test code from instantiating a robot because doing so might cause WPILib to try to start a NetworkTables server when another test already has one running.

### CODE REVIEW

File: plugin/libdeepbluesim/src/main/java/org/carlmontrobotics/libdeepbluesim/WebotsSimulator.java [hunk 1]
```diff
@@ -86,15 +103,59 @@ public class WebotsSimulator implements AutoCloseable {
...
-     * @throws FileNotFoundException if the world file does not exist
+     * @param cls the class of the TimedRobot to run.
+     * @throws InterruptedException if interrupted while waiting to get exclusive use of the needed
+     *         TCP ports.
+     * @throws IOException if an IO error occurs while attempting to get exclusive use of the needed
+     *         TCP ports.
      */
-    public WebotsSimulator(String worldFilePath) throws FileNotFoundException {
+    public WebotsSimulator(String worldFilePath,
+            Class<? extends TimedRobot> cls)
```
Comment (CoolSpy3) [inline plugin/libdeepbluesim/src/main/java/org/carlmontrobotics/libdeepbluesim/WebotsSimulator.java:156]: I'd recommend taking a `Supplier<TimedRobot>` instead, and then passing `Robot::new` instead of `Robot.class`. This would allow you to avoid the reflection later and support robot classes with non-default constructors.

File: plugin/libdeepbluesim/src/main/java/org/carlmontrobotics/libdeepbluesim/WebotsSimulator.java [hunk 2]
```diff
@@ -86,15 +103,59 @@ public class WebotsSimulator implements AutoCloseable {
...
+
+    static {
+        try {
+            acquireFileLock();
+        } catch (InterruptedException | IOException ex) {
+            LOG.log(Level.ERROR, "Unable to acquire file lock", ex);
+        }
+    }
+
+    static private synchronized void acquireFileLock()
```
Comment (CoolSpy3) [inline plugin/libdeepbluesim/src/main/java/org/carlmontrobotics/libdeepbluesim/WebotsSimulator.java:116]:
```suggestion
    private static synchronized void acquireFileLock()
```

**Review by CoolSpy3 — APPROVED** [review]
Nice! You opened this *while* I was writing you a mattermost message about tests not working on my machine. This PR fixes that! :D

Side note: The first time I ran this, `testShaftRotatesInAutonomous` failed, but I've tried it again, and it seems to work now, so it may just be a case of a non-ideal testing environment (i.e. me running too many programs at once).

**Comment by CoolSpy3** [comment]
Whoops, I hit approve while forgetting that I had suggestions (too excited about getting tests working) :/ My bad.

**Comment by brettle** [comment]
> The first time I ran this, `testShaftRotatesInAutonomous` failed, but I've tried it again, and it seems to work now, so it may just be a case of a non-ideal testing environment

Opened issue #94 to cover this.
